### PR TITLE
fix bug with room editor overflowing tile grid

### LINKED ISSUE #50: Editor changing tile ids when exporting game or copy/pasting game data
Sometimes the editor will add an extra letter to a tile within a room (typically a duplicate letter/number). The changed tile is usually one from the right side of the room.

Has happened both when exporting and when pasting game data into an html file. I've only tested it on chrome, so I'm not sure if it's an issue specific to that browser or not.

bitsy bug

### PR DESCRIPTION
**Pull request by zachThePerson**
Closes #50

### CODE REVIEW

File: editor/script/room.js [hunk 1]
```diff
@@ -195,6 +195,10 @@ function RoomTool(canvas) {
 		isDragDeletingTiles = false;
 	}
 
+	function clamp(val, min, max){
```
Comment (le-doux) [inline editor/script/room.js]: nice work!

this is a nitpick (and I realize there isn't a very consistent code style in bitsy D:) but I like to put a space before the opening parentheses of a function definition :)

otherwise, this looks great!
